version: "3.8"

services:
  backend:
    build: ./codenotes-backend
    ports:
      - "3000:3000"
    volumes:
      - ./codenotes-backend:/app
      - ./codenotes-backend/data:/app/data
    environment:
      - NODE_ENV=development

  frontend:
    build: ./codenotes-frontend
    ports:
      - "5000:5000"
    volumes:
      - ./codenotes-frontend:/app
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend